CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    amount   BIGINT  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id   BIGINT  NOT NULL,
    departure VARCHAR NOT NULL,
    arrival   VARCHAR NOT NULL,
    segments  BIGINT  NOT NULL,
    price     BIGINT  NOT NULL,
    currency  VARCHAR NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE routes
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    departure VARCHAR NOT NULL,
    arrival   VARCHAR NOT NULL,
    segments  BIGINT  NOT NULL
);
